### ISSUE TITLE
Unattended Upgrades funktionieren nicht

### ISSUE THREAD

**Issue by fabianhauser** [studentenportal/deploy#22]
Ich habe gerade manuell upgrades installiert - offenbar funktioniert dies nicht automatisch.

**Comment by dbrgn** [comment]
Ich glaube unattended-upgrades installiert standardmässig nur Security Updates. Waren das bei dir Security Updates oder reguläre Updates?

**Comment by fabianhauser** [comment]
> Ich glaube unattended-upgrades installiert standardmässig nur Security Updates. Waren das bei dir Security Updates oder reguläre Updates?

Hmm, habe ich nicht drauf geachtet. Ich wäre eh dafür, alle Updates (inkl. automatischem reboot) durchzuführen...
