### ISSUE TITLE
Automatisierte Backups

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/deploy#6]
z.B. mit [Borg Backup](https://www.borgbackup.org/) - ist aber für mich momentan out of scope, weil nie genauer abgesprochen und auf dem alten Host auch nicht vorhanden.

**Comment by fabianhauser** [comment]
@Murthy10 falls ihr nochmal einen Auftrag vom open\HSR / open\OST umsetzt: Dieses Issue wäre aus meiner Sicht recht wichtig, @Stautob hat vermutlich erfahrung mit `borg` oder `restic`.

**Comment by The-Compiler** [comment]
So, wir haben endlich Backups :sparkles:

Die SQL-Datenbank wird täglich nach `/var/backups/sql/` gedumpt (für 2 Jahre, ein Backup ist nur ca. 25MB), und die Daten landen via Duply wöchentlich auf dem Hostpoint-FTP (für 6 Monate, dabei alle 2 Monate ein volles Backup, danach jeweils inkrementell).

Wir haben (zusammen mit dem VSHSR?) auf dem Hostpoint-Server 50 GB Platz, davon momentan ca. 3 GB genutzt. Ein volles Backup ist momentan ca. 5GB gross. Sollte also hoffentlich hinkommen. :crossed_fingers:
